### ISSUE TITLE
Add pause to the game

### ISSUE THREAD

**Issue by KarinaKuznecova** [KarinaKuznecova/Animal-Shelter-Game#203]
By pressing esc

**Comment by Sohamkayal4103** [comment]
Can I work on this?

**Comment by KarinaKuznecova** [comment]
> Can I work on this?

Yes, go on. If you will have any questions - feel free to ask.

**Comment by KarinaKuznecova** [comment]
Hi @Sohamkayal4103 
Are you still working on it? Do you need any help?

**Comment by KarinaKuznecova** [comment]
Well, more than a month passed since you picked up this task, I assume you don't work on it anymore.
