### ISSUE TITLE
Can't start the project.

### ISSUE THREAD

**Issue by Parneet-Raghuvanshi** [KarinaKuznecova/Animal-Shelter-Game#371]
When running this project it shows some storage classes missing.

![image](https://user-images.githubusercontent.com/54593571/229310133-eca8a42a-5274-410c-911b-7516b2cef562.png)

maybe I am missing something with the setup, or any property to adjust?

**Comment by KarinaKuznecova** [comment]
Hi @Parneet-Raghuvanshi 
Thanks for letting me know. I added some changes to the main branch. Can you try again? I hope now it will work. But if not - let me know and I will check again

**Comment by Parneet-Raghuvanshi** [comment]
It worked, thanks!

**Comment by Parneet-Raghuvanshi** [comment]
Actually, these types of games are very satisfying, I have played a lot of Len's Island.
https://store.steampowered.com/app/1335830/Lens_Island/
Will try to look into this project to improve more, and add more customization.

Do you have any future plans to improve this project (graphically)?

**Comment by KarinaKuznecova** [comment]
No, I don't plan big improvements. Maybe I will re-draw some sprites, so they all will be in one style, but I will keep it in 2D. Maybe next project will be prettier :)

**Comment by Parneet-Raghuvanshi** [comment]
Oh, that's fine.
It's still good and conceptual, thanks for the info!
