### ISSUE TITLE
Eating raw food should fulfill only by 25 %

### ISSUE THREAD

**Issue by KarinaKuznecova** [KarinaKuznecova/Animal-Shelter-Game#376]
So this task requires changes somewhere in EatingState.
I think it should be like that:
raw food to fill hunger by 25%,
simple meal to fill hunger by 50%
tasty meal to fill hunger by 75%
and perfect meal to fill hunger to 100%

**Comment by schrapsi** [comment]
Hey,
i like your game thats why i  want to contribute to you project. I saw this issue labeled as easy that's why i want to try to do this.
Can you explain in more detail what you mean by "raw food". And are the animals meant by eating ? 
Because as far as i understand your code only animals can eat. Is that correct ?

**Comment by KarinaKuznecova** [comment]
Hi @schrapsi 
Sorry if I don't have much details in Issues, I was writing it mostly for myself. But I am happy that someone wants to contribute to my project. 
I just pushed new code couple of minutes ago, that introduced "cooked food". Cooked food is represented by class `PetFood`, and only `PetFood` now could be put in food bowl.
"Raw food" - everything not in food bowl and that animal can eat, it should be crops that are collected from plants. 

So this task requires changes somewhere in `EatingState`. 
I think it should be like that:
raw food to fill hunger by 25%, 
simple meal to fill hunger by 50%
tasty meal to fill hunger by 75%
and perfect meal to fill hunger to 100%

I already added `String foodType;` to `FoodBowl` class, it could be used to determine what type of food is in the bowl.

Feel free to ask if something is not clear or if you need any help :)
