### ISSUE TITLE
Create NameService and store names in json

### ISSUE THREAD

**Issue by KarinaKuznecova** [KarinaKuznecova/Animal-Shelter-Game#400]
Move current logic out of AnimalService to new NameService
And sort names alphabetically in file

**Comment by schrapsi** [comment]
Im working on this issue right now.
You want the names in the new json file sortet. Right ?

**Comment by KarinaKuznecova** [comment]
Hi @schrapsi 
Yes, I want the names in the new json file, sorted alphabetically 
Right now they are in txt files (https://github.com/KarinaKuznecova/Animal-Shelter-Game/blob/master/config/names-m.txt and https://github.com/KarinaKuznecova/Animal-Shelter-Game/blob/master/config/names-f.txt), but should be in json, also separated by languages.

**Comment by schrapsi** [comment]
Okay.
I wrote some code. I don't think its finished yet but can you take a look and tell me if i did it like you want it ? 
Should i just create a PR for you ? Or how does that work when the work on the Issue isn't done yet?

**Comment by KarinaKuznecova** [comment]
Yes, just create PR, I will take a look. 

Also you can test by launching the game, check if animals still get random names when found.

Steps to check:
1. launch game, wait for some time (in logs there should be "cat/dog/etc in the bush" or something similar)
2. then go near big bushes (2 on main map, and some in the forest (location to the right))
3. if there is a heart above the bush - animal is inside.
4. click on the bush
5. new animal should appear nearby
6. click on new animal icon
7. check if new animal has a name from the list
